plugins {
    id 'com.android.application'
}

android {
    namespace 'org.citizenscience.turbimeter'
    compileSdk 36

    defaultConfig {
        applicationId 'org.citizenscience.turbimeter'
        minSdk 26
        targetSdk 36
        versionCode 3
        versionName '0.3'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
